feat(KDL): KDL6-5 Create users
konstellation-io/kdl-server pull request #1016
Opened 2024-11-06 14:29 UTC by igzjaviergil

## Motivation and Context

As new users are logged in KDL, they need to be
created as new users. Meaning, creating new user in database and corresponding k8s resources.
Place to insert new user is auth middleware.
Add auth middleware tests.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] I have created tests for my code changes, and the tests are passing.
- [X] I have executed the pre-commit hooks locally.
- [ ] I have updated the documentation accordingly.
- [X] The commit message follows our guidelines: https://github.com/konstellation-io/kdl-server/blob/main/CONTRIBUTING.md
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] My change requires a change to the documentation (create a new issue if the documentation has not been updated).

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Closes #

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

2024-11-06 16:18 UTC, alexrodfe commented on app/api/http/middleware/auth.go
> +func AuthMiddleware(next http.Handler, userCase user.UseCase) http.Handler {
perhaps we could call the userCase variable as userUsecase?
what do you think?

2024-11-06 16:20 UTC, alexrodfe commented on app/api/http/middleware/auth.go
> +				w.WriteHeader(http.StatusInternalServerError)
this is the top level of error handling, so this err!=nil should print an error log

2024-11-06 16:22 UTC, alexrodfe commented on app/api/http/middleware/auth_test.go
> +	mocks      userMocks
clever!

2024-11-06 16:33 UTC, alexrodfe commented on app/api/usecase/user/interactor.go
> +var _ UseCase = (*UserInteractor)(nil)
I see :eyes:

2024-11-06 16:34 UTC, alexrodfe commented on app/api/usecase/user/interactor.go
> +type UserInteractor struct {
Interaction as with a capital letter is still good naming
as this is user.UserInteractor
and we could have it as user.Interactor

2024-11-06 16:36 UTC, alexrodfe requested changes
Hey good work, a couple notes here

2024-11-07 07:34 UTC, igzjaviergil commented on app/api/http/middleware/auth.go
> +func AuthMiddleware(next http.Handler, userCase user.UseCase) http.Handler {
it make sense :)

2024-11-07 07:35 UTC, igzjaviergil commented on app/api/http/middleware/auth.go
> +				w.WriteHeader(http.StatusInternalServerError)
you mean print + adding internal server error header right?

2024-11-07 07:46 UTC, igzjaviergil commented on app/api/http/middleware/auth.go
> +				w.WriteHeader(http.StatusInternalServerError)
mmm I can see we need to set zapper just for one line. is it really that important? or can we logged inside Create? Open discussion

2024-11-08 11:50 UTC, igzjaviergil commented on app/api/http/middleware/auth.go
> +				w.WriteHeader(http.StatusInternalServerError)
Discussed between us and decided that loggers inside `userUsecase.Create` are enough and there is no need to add extra logs in middleware at the moment

2024-11-19 15:25 UTC, alexrodfe commented on app/api/usecase/user/interactor_test.go
> +	require.Equal(t, someErr, err)
Instead of checking if errors are equal, another more resilient check is to:
- Check: require.Error(err)
- Check: assert.ErrorIs(ErrUserNotFound, err)

2024-11-19 17:05 UTC, alexrodfe approved these changes

2024-11-19 17:06 UTC, merged