feat(ui): remove gitea
konstellation-io/kdl-server pull request #1032
Opened 2024-11-20 11:12 UTC by alexrodfe

## Motivation and Context

Remove all Gitea components from UI.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] I have created tests for my code changes, and the tests are passing.
- [ ] I have executed the pre-commit hooks locally.
- [ ] I have updated the documentation accordingly.
- [ ] The commit message follows our guidelines: https://github.com/konstellation-io/kdl-server/blob/main/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] My change requires a change to the documentation (create a new issue if the documentation has not been updated).

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Closes #

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2024-11-20 11:54 UTC, igzjaviergil requested changes

2024-11-20 11:54 UTC, igzjaviergil commented on app/ui/public/config.json
> -  "GITEA_URL": "https://gitea.local",
this change may affect helm-chart, please double check with @ialejandro

2024-11-20 11:54 UTC, igzjaviergil commented on app/ui/src/Pages/Project/panels/ProjectSettings/components/TabGit/TabGit.tsx
> -      {isAdmin && isExternal && (
removing entire block of code avoid possibility to edit project, is that correct?

2024-11-20 12:22 UTC, ialejandro commented on app/ui/public/config.json
> -  "GITEA_URL": "https://gitea.local",
I'll remove from my side too, thx @igzjaviergil

2024-11-20 16:40 UTC, alexrodfe commented on app/ui/src/Pages/Project/panels/ProjectSettings/components/TabGit/TabGit.tsx
> -      {isAdmin && isExternal && (
I have my own set of doubts as well, however check that the URL the selector navigates to is a Gitea one, and we are deprecating all Gitea. So I believe this service won't be available and there will be no place to go to edit

2024-11-20 16:57 UTC, igzjaviergil commented on app/ui/src/Pages/Project/panels/ProjectSettings/components/TabGit/TabGit.tsx
> -      {isAdmin && isExternal && (
true indeed

2024-11-20 16:57 UTC, igzjaviergil approved these changes

2024-11-21 07:06 UTC, kafkaphoenix approved these changes

2024-11-21 11:20 UTC, merged