feat(api): [KDL6-181] deprecate repository type
konstellation-io/kdl-server pull request #1064
Opened 2024-12-03 16:43 UTC by alexrodfe

## Motivation and Context
Deprecate repository type from all logic in api. Repository type was relevant for Gitea repos, however Gitea has been deprecated.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] I have created tests for my code changes, and the tests are passing.
- [ ] I have executed the pre-commit hooks locally.
- [ ] I have updated the documentation accordingly.
- [ ] The commit message follows our guidelines: https://github.com/konstellation-io/kdl-server/blob/main/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] My change requires a change to the documentation (create a new issue if the documentation has not been updated).

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Closes #

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2024-12-17 17:33 UTC, igzjaviergil requested changes
Let's move UPGRADE_GUIDE.md to some other place, it may be confusing to find that in the root path.

2024-12-18 10:48 UTC, igzjaviergil approved these changes

2024-12-18 10:54 UTC, kafkaphoenix approved these changes

2024-12-18 10:55 UTC, igzjaviergil commented on app/api/infrastructure/mongodb/project.go
> +	URL                string                      `bson:"url"`
I see you have created a guide to do the migration, thanks!

2024-12-18 10:55 UTC, igzjaviergil commented on app/graphql/schema.graphqls
> -  regenerateSSHKey: User!
clear now, thanks!

2024-12-18 11:00 UTC, merged