feat: [KDL6-206] add labels to secrets
konstellation-io/kdl-server pull request #1079
Opened 2024-12-12 14:36 UTC by igzjaviergil

## Motivation and Context

Add label konstellation.io/ssh-key: true to <user>-ssh-keys 
Add label konstellation.io/secret-service-account-token: true to <user>-service-account-secret
Add tests

## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] I have created tests for my code changes, and the tests are passing.
- [X] I have executed the pre-commit hooks locally.
- [ ] I have updated the documentation accordingly.
- [X] The commit message follows our guidelines: https://github.com/konstellation-io/kdl-server/blob/main/CONTRIBUTING.md
- [X] Tests for the changes have been added (for bug fixes / features)
- [ ] My change requires a change to the documentation (create a new issue if the documentation has not been updated).

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [X] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Closes #

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [X] No

## Other information

2024-12-12 14:47 UTC, alexrodfe commented on app/api/http/main.go
> +	srv.AddTransport(transport.POST{})
I'd add here as well:

```
	srv.AddTransport(transport.GET{})
	srv.AddTransport(transport.POST{})
	srv.AddTransport(transport.MultipartForm{})
	``

2024-12-12 14:50 UTC, alexrodfe commented on app/api/infrastructure/k8s/config.go
> +package k8s
for starters this file should end with '_test.go' so, a its proper name should be: 'config_test.go'

2024-12-12 14:51 UTC, alexrodfe commented on app/api/infrastructure/k8s/config.go
> +package k8s
An the first line should include the "go build tag integration"

2024-12-12 15:15 UTC, alexrodfe requested changes

2024-12-12 15:15 UTC, alexrodfe commented on app/api/infrastructure/k8s/config.go
> +package k8s
also package should be `k8s_test`

2024-12-12 15:15 UTC, alexrodfe commented on app/api/infrastructure/k8s/user_ssh.go
> +	labels = map[string]string{
watchout, you are overwritting "labels" value here

2024-12-12 15:31 UTC, igzjaviergil commented on app/api/http/main.go
> +	srv.AddTransport(transport.POST{})
I wanted to be more restrictive, but indeed it was like this before so keeping it

2024-12-12 15:31 UTC, igzjaviergil commented on app/api/infrastructure/k8s/config.go
> +package k8s
noted!

2024-12-12 16:09 UTC, igzjaviergil commented on app/api/infrastructure/k8s/user_ssh.go
> +	labels = map[string]string{
well spotted, I just copied pasted and didn´t realized

2024-12-13 11:10 UTC, alexrodfe submitted a review, later dismissed

2024-12-13 11:38 UTC, alexrodfe approved these changes

2024-12-13 11:44 UTC, merged