Feat/kg grpc client
konstellation-io/kdl-server pull request #108
Opened 2021-02-19 16:47 UTC by angeltabar

2021-02-22 15:13 UTC, angelsanchez commented on app/api/infrastructure/kgservice/service.go
> +		}
The KnowledgeGraphItemCat type is string.
The value.Category is string.
So you can use:
```
cat := entity.KnowledgeGraphItemCat(value.Category)
if !cat.IsValid() {
   return ....
}
```

2021-02-22 15:19 UTC, angelsanchez commented on app/api/infrastructure/kgservice/service.go
> +		}
why not a function that returns the str pointer or nil if the string is empty:
```
func stringToPointer(s string) *string {
  if s == "" {
    return nil
  }
  return &s
}
```
with this helper func:
```
items[i] = entity.KnowledgeGraphItem{
....
			ExternalID:  stringToPointer(value.ExternalId),
			Framework:   stringToPointer(value.Framework),
		}
```

2021-02-22 15:32 UTC, angelsanchez commented on app/api/usecase/kg/interactor.go
> +type Interactor struct {
Interactor should be private `interactor`

2021-02-22 15:33 UTC, angelsanchez requested changes

2021-02-22 15:33 UTC, angelsanchez commented on app/api/usecase/kg/interactor.go
> +	kgService kgservice.KGService) *Interactor {
should return a interface `kg.UseCase`

2021-02-22 17:21 UTC, marcvivancos approved these changes

2021-02-22 17:24 UTC, angeltabar commented on app/api/infrastructure/kgservice/service.go
> +		}
value.Category comes in lowercase. The output is capitalized to validate it. We are not super sure if this is the best way to do it

2021-02-23 11:57 UTC, angelsanchez approved these changes

2021-02-23 11:58 UTC, merged