feat(ui): KDL6-130 Remove Repository Type
konstellation-io/kdl-server pull request #1088
Opened 2024-12-17 13:02 UTC by joancarballo

## Motivation and Context

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] I have created tests for my code changes, and the tests are passing.
- [ ] I have executed the pre-commit hooks locally.
- [ ] I have updated the documentation accordingly.
- [ ] The commit message follows our guidelines: https://github.com/konstellation-io/kdl-server/blob/main/CONTRIBUTING.md
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] My change requires a change to the documentation (create a new issue if the documentation has not been updated).

## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## What is the current behavior?

Closes #

## What is the new behavior?

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

## Other information

2024-12-18 15:27 UTC, igzjaviergil requested changes

2024-12-18 15:27 UTC, igzjaviergil commented on app/ui/src/Graphql/client/hooks/useNewProject.ts
> +  // ExternalRepositoryValues,
letś remove evertyhing and avoid leaving comments in code

2024-12-18 15:27 UTC, igzjaviergil commented on app/ui/src/Mocks/entities/project.ts
> +// import { RepositoryType } from '../../Graphql/types/globalTypes';
same here

2024-12-18 15:27 UTC, igzjaviergil commented on app/ui/src/Pages/NewProject/NewProject.tsx
> +// import { RepositoryType } from 'Graphql/types/globalTypes';
ditto

2024-12-18 15:27 UTC, igzjaviergil commented on app/ui/src/Pages/Project/pages/Overview/Overview.tsx
> +// import { RepositoryType } from 'Graphql/types/globalTypes';
ditto

2024-12-18 15:27 UTC, igzjaviergil commented on app/ui/src/Pages/NewProject/pages/Repository/Repository.tsx
> +// import { RepositoryType } from 'Graphql/types/globalTypes';
ditto

2024-12-18 15:27 UTC, igzjaviergil commented on app/ui/src/Pages/Projects/components/Project/Project.tsx
> +    {/* <div className={styles.label}>{capitalize(project.repository?.type)}</div> */}
ditto

2024-12-19 08:39 UTC, joancarballo commented on app/ui/src/Graphql/client/hooks/useNewProject.ts
> +  // ExternalRepositoryValues,
Deleted this and related.

2024-12-19 08:39 UTC, joancarballo commented on app/ui/src/Mocks/entities/project.ts
> +// import { RepositoryType } from '../../Graphql/types/globalTypes';
Deleted this and related.

2024-12-19 08:40 UTC, joancarballo commented on app/ui/src/Pages/Project/pages/Overview/Overview.tsx
> +// import { RepositoryType } from 'Graphql/types/globalTypes';
Deleted this and related.

2024-12-19 08:40 UTC, joancarballo commented on app/ui/src/Pages/NewProject/NewProject.tsx
> +// import { RepositoryType } from 'Graphql/types/globalTypes';
Deleted this and related.

2024-12-19 08:40 UTC, joancarballo commented on app/ui/src/Pages/NewProject/pages/Repository/Repository.tsx
> +// import { RepositoryType } from 'Graphql/types/globalTypes';
Deleted this and related.

2024-12-19 08:40 UTC, joancarballo commented on app/ui/src/Pages/Projects/components/Project/Project.tsx
> +    {/* <div className={styles.label}>{capitalize(project.repository?.type)}</div> */}
Deleted this and related.

2024-12-19 08:42 UTC, igzjaviergil approved these changes

2024-12-19 11:13 UTC, merged