Feat/user creation
konstellation-io/kdl-server pull request #40
Opened 2021-02-05 13:55 UTC by angelsanchez

2021-02-08 10:08 UTC, guumaster requested changes

2021-02-08 10:08 UTC, guumaster commented on app/api/infrastructure/repository/user.go
> +	"go.mongodb.org/mongo-driver/mongo/options"
sort imports with IDE linter 
- built-in
- external
- current app/module

2021-02-09 10:13 UTC, guumaster commented on app/api/pkg/giteaclient/client.go
> +func (g *GiteaClientHTTP) CreateUser(email, username, password string) (*NewUser, error) {
There is an official library to interact with Gitea, maybe you can take a look at it:
https://pkg.go.dev/code.gitea.io/sdk/gitea

2021-02-09 10:28 UTC, angelsanchez commented on app/api/pkg/giteaclient/client.go
> +func (g *GiteaClientHTTP) CreateUser(email, username, password string) (*NewUser, error) {
thanks we are going to try it

2021-02-10 11:59 UTC, merged