Create KG gRPC server
konstellation-io/kdl-server pull request #49
Opened 2021-02-09 17:15 UTC by marcvivancos

Adds an initial version of the gRPC server for the KG, closes #15.

2021-02-10 10:51 UTC, IGZVasjaUrbancic requested changes
Very nice work! I think one item really needs changing before merging, which is relating to the comment on scores and distances in `Recommender.get_top_items()`. Other comments I made are suggestions for improvement but are not essential to address before merging. Thank you Marc, great work!

2021-02-10 10:51 UTC, IGZVasjaUrbancic commented on kg/src/recommender.py
> +        df_subset = df_subset.sort_values(by=['score'], ascending=True).head(n_hits)
This implementation assumes that lowest score is better, whereas I believe the front designs assume the opposite. Equating score with distance here has the potential to quietly break the recommender to return highest-distance hits instead of lowest-distance hits. This code needs revising upon the completion of issue #46. In the meantime, I suggest implementing a placeholder `convert_distance_to_score = lambda x: 1-x` to avoid the risk outlined above.

2021-02-10 10:51 UTC, IGZVasjaUrbancic commented on kg/src/recommender.py
> +        df_subset = df_subset.sort_values(by=['score'], ascending=True).head(n_hits)
Accordingly, to avoid assigning distances to scores, we can use something similar to: 

```
(line 90) scores = [convert_distance_to_score(d) for d in distances]
...
(line 92) df_subset['score'] = scores
```

2021-02-10 10:51 UTC, IGZVasjaUrbancic commented on kg/tests/unit/test_recommender.py
> +        assert papers.items[0].title == "test title"
These assertions all test for useful things, but they test fairly diverse aspects, including the structure of the outputs. In the name of making unit tests more atomic, would it make sense to break this test down into three tests that share a common fixture (lines 40-46) but explicitly test a different aspect each? 

Specifically, some assertions here are testing code that is outside the responsibility of the `Recommender`: line 49, `assert isinstance(papers.items[0], outputs.RecommendedItem)` is in fact testing the `RecommendedList` data class rather than Recommender, so I wonder if they may be better placed elsewhere (`test_outputs.py`). Alternatively, simply separating this out into three tests and giving each of them an explicit name for what exactly it is testing may be enough. 

This is not essential, it's just a suggestion for improvement for long-term maintainability if you agree that it would help and if time permits.

2021-02-10 10:51 UTC, IGZVasjaUrbancic commented on kg/tests/unit/test_tools_assets.py
> +            AssetLoader._asset_checks(assets_mock)
I suggest adding a happy-path test here, i.e. a case where AssetLoader is able to successfully load the provided dataset and vectors.

In addition, that's a minute detail, but would it make sense to match the actual expected input types (i.e. np array of floats for vectors, data frame for dataset) in the test case? They all implement __len__, so at the moment it won't make a practical difference, but if in the future we decide for example to create our own data class instead of a data frame for `dataset`, having the actual class of the asset inside this test would be useful to make sure it behaves correctly.

2021-02-10 10:51 UTC, IGZVasjaUrbancic commented on kg/tests/unit/test_recommender.py
> +    def test_preprocess(self):
I suggest a test name that explicitly states what exactly it tests for, e.g. `test_that_preprocess_removes_newline_characters`

2021-02-10 10:51 UTC, IGZVasjaUrbancic commented on kg/src/recommender.py
> +        """
It may be useful to specify the expected shapes of input and output vectors in the docstring, as it is intended to be used within the recommender. `(1, vector_dimensions)` representing the query vector in `vectors_1` ,  `(N_HITS, vector_dimensions)` representing the dataset vectors for `vectors_2`, and `(N_HITS, 1)` for output (or something similar, not sure exactly).

2021-02-10 10:51 UTC, IGZVasjaUrbancic commented on kg/src/outputs.py
> +class RecommendedList:
Maybe a brief docstring here as well?

2021-02-10 10:51 UTC, IGZVasjaUrbancic commented on kg/.flake8
> +exclude = tests/*,.git,__pycache__,proto,.github/
Are tests excluded on purpose?

2021-02-10 15:45 UTC, angelsanchez requested changes

2021-02-10 15:45 UTC, angelsanchez commented on kg/.editorconfig
> +max_line_length = 119
Why the max_line_length (119) is different than .flake8 (115) configuration?

2021-02-10 15:45 UTC, angelsanchez commented on kg/README.md
> +python src/app.py
```suggestion
pipenv run python src/app.py
```
the python interpreter should be the located inside the virtual env instead of the installed in the path.

2021-02-10 15:45 UTC, angelsanchez commented on kg/README.md
> +python -m pytest -m "not int"
```suggestion
pipenv run pytest -m "not int"
```

2021-02-10 15:45 UTC, angelsanchez commented on kg/README.md
> +python src/app.py
```suggestion
pipenv run python src/app.py
```

2021-02-10 15:45 UTC, angelsanchez commented on kg/README.md
> +python -m pytest int
```suggestion
pipenv run pytest int
```

2021-02-10 15:45 UTC, angelsanchez commented on kg/src/recommender.py
> +log = logging.getLogger("Recommender")
Consider to use a class member like other classes, e.g.
```
self.log = logging.getLogger("KGApp")
```

2021-02-17 12:37 UTC, angelsanchez approved these changes

2021-02-17 13:21 UTC, IGZVasjaUrbancic approved these changes
All good :+1:  Thank you Marc!

2021-02-18 07:18 UTC, merged