add get user list functionality
konstellation-io/kdl-server pull request #56
Opened 2021-02-10 17:21 UTC by angeltabar

2021-02-11 10:05 UTC, angelsanchez requested changes

2021-02-12 09:06 UTC, angeltabar commented on app/api/entity/error.go
> +	ErrListUsersEmpty = errors.New("user list empty")
removed

2021-02-12 09:07 UTC, angeltabar commented on app/api/infrastructure/repository/user.go
> +		if errors.Is(err, mongo.ErrNoDocuments) {
that's true. Fix done

2021-02-12 10:37 UTC, angelsanchez requested changes

2021-02-12 10:37 UTC, angelsanchez commented on app/api/infrastructure/graph/schema.resolvers.go
> +	return users, nil
unnecessary code
```suggestion
return  r.users.FindAll(ctx)
```

2021-02-12 10:53 UTC, angeltabar commented on app/api/infrastructure/graph/schema.resolvers.go
> +	return users, nil
done!

2021-02-12 10:59 UTC, merged