refactor(ui): two big tooltips to an independent component
konstellation-io/kdl-server pull request #747
Opened 2022-03-07 10:05 UTC by rrbarrero

There was two big tooltips that needed refactoring in the NavElements component.

2022-03-08 10:11 UTC, rrbarrero commented
* Moved new tooltip component to a common location
* Refactored all instances of ReactTooltip
* Added original ReactTooltip properties so it can be styled

2022-03-08 13:23 UTC, JYisus requested changes

2022-03-08 13:23 UTC, JYisus commented on app/ui/src/Components/Tooltip/Tooltip.tsx
> +  cssId: string;
@rrbarrero Maybe tooltipId is a better name for this prop since this is not exactly an id used in css

2022-03-09 07:11 UTC, alejandrogr approved these changes

2022-03-09 07:45 UTC, rrbarrero reviewed
Done

2022-03-09 12:08 UTC, merged