feat(user-tools-operator): pass Jupyter kernels the name of the shared volume PVC
konstellation-io/kdl-server pull request #784
Opened 2022-04-08 14:13 UTC by alpiquero

This PR modifies the user-tools-operator statefullset definition to allow the Jupyter container to pass Jupyter Kernels the name of the shared PVC via the `KERNEL_SHARED_VOLUME_NAME` environment variable.

Must be merged after #783 

Related #783

2022-04-11 06:21 UTC, blopezpi requested changes
This change doesn't fix the root problem. And you need to named as fix because this is not a feature.

2022-04-11 06:39 UTC, alpiquero commented
> This change doesn't fix the root problem. And you need to named as fix because this is not a feature.

Done!

2022-04-12 06:08 UTC, aacecandev approved these changes

2022-04-12 08:47 UTC, blopezpi approved these changes

2022-04-18 06:57 UTC, merged